# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: Build and Push docker image
  displayName: 'Build and Push docker image'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub CS'
    command: 'login'

- task: Docker@2
  displayName: Build and Push
  inputs:
    containerRegistry: 'Docker Hub CS'
    repository: 'phmonte/azdevops-agent-ubuntu1804-python-cache'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest

- task: Docker@2
  displayName: Build and Push
  inputs:
    containerRegistry: 'Docker Hub CS'
    repository: 'phmonte/azdevops-agent-win-python-cache'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest