# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:
- script: Build and Push docker image
  displayName: 'Build and Push docker image'

- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      dir
