# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Ubuntu
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: Docker@2
    displayName: Build and Push
    inputs:
      containerRegistry: 'Docker Hub CS'
      repository: 'phmonte/azdevops-agent-ubuntu1804-python-cache'
      command: 'buildAndPush'
      Dockerfile: '**/ubuntu1804/Dockerfile'
      tags: |
        $(Build.BuildId)
        latest

- job: Windows
  pool:
    vmImage: windows-latest
  steps:
  - task: Docker@2
    displayName: Build and Push
    inputs:
      containerRegistry: 'Docker Hub CS'
      repository: 'phmonte/azdevops-agent-win-python-cache'
      command: 'buildAndPush'
      Dockerfile: '**/windows2019/Dockerfile'
      tags: |
        $(Build.BuildId)
        latest
